// Copyright (c) Meta Platforms, Inc. and affiliates.
import {createHash} from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  assertWithin,
  PathSafetyError,
} from '../../../../foundation/fs/path-safety.mjs';
import {ERROR_CODES} from '../../../../foundation/response/error-codes.mjs';
import {AstryxError} from '../../../error.mjs';
import {generatePaletteSet, serializeGenerationResult} from './generator.mjs';
import {PALETTE_PREVIEW_VERSION, renderPalettePreview} from './preview.mjs';

function paletteSnapshot(result) {
  return {
    schemaVersion: 1,
    status: 'candidate',
    recipe: result.recipe,
    palette: Object.fromEntries(
      result.families.map(family => [
        family.id,
        {
          name: family.name,
          ...(family.light ? {light: family.light.colors} : {}),
          ...(family.dark ? {dark: family.dark.colors} : {}),
        },
      ]),
    ),
  };
}

function serializePaletteModule(candidate) {
  return `// Generated by ${candidate.recipe}. Review before committing.\nexport const palette = ${JSON.stringify(candidate.palette, null, 2)} as const;\n\nexport default palette;\n`;
}

function serializeCandidate(candidate, outputPath) {
  if (outputPath.endsWith('.ts')) return serializePaletteModule(candidate);
  if (outputPath.endsWith('.json'))
    return `${JSON.stringify(candidate, null, 2)}\n`;
  throw new AstryxError(
    'Palette output must end in .ts or .json.',
    undefined,
    ERROR_CODES.ERR_PALETTE_GENERATION,
  );
}

function receiptFor(result, candidateText, previewText = null) {
  return {
    schemaVersion: 1,
    recipe: result.recipe,
    candidateSha256: createHash('sha256').update(candidateText).digest('hex'),
    ...(previewText
      ? {
          preview: {
            version: PALETTE_PREVIEW_VERSION,
            sha256: createHash('sha256').update(previewText).digest('hex'),
          },
        }
      : {}),
    request: result.request,
    diagnostics: {
      families: Object.fromEntries(
        result.families.map(family => [
          family.id,
          {
            ...(family.light ? {light: family.light.diagnostics} : {}),
            ...(family.dark ? {dark: family.dark.diagnostics} : {}),
          },
        ]),
      ),
      coordination: result.coordination,
    },
  };
}

function receiptPathFor(candidatePath) {
  const extension = path.extname(candidatePath);
  return extension
    ? `${candidatePath.slice(0, -extension.length)}.receipt.json`
    : `${candidatePath}.receipt.json`;
}

function resolveSafe(targetPath, cwd, label) {
  try {
    return assertWithin(targetPath, cwd, {label});
  } catch (error) {
    if (error instanceof PathSafetyError) {
      throw new AstryxError(
        error.message,
        undefined,
        ERROR_CODES.ERR_PATH_TRAVERSAL,
      );
    }
    throw error;
  }
}

function writeFilesAtomically(files) {
  const originals = files.map(file => ({
    ...file,
    existed: fs.existsSync(file.path),
    contents: fs.existsSync(file.path) ? fs.readFileSync(file.path) : null,
    temporary: `${file.path}.tmp-${process.pid}`,
  }));
  try {
    for (const file of originals) {
      fs.mkdirSync(path.dirname(file.path), {recursive: true});
      fs.writeFileSync(file.temporary, file.next);
    }
    for (const file of originals) fs.renameSync(file.temporary, file.path);
  } catch (error) {
    for (const file of originals) {
      try {
        if (fs.existsSync(file.temporary)) fs.unlinkSync(file.temporary);
        if (file.existed) fs.writeFileSync(file.path, file.contents);
        else if (fs.existsSync(file.path)) fs.unlinkSync(file.path);
      } catch {
        // Recovery is best effort; preserve the original write error.
      }
    }
    throw error;
  }
}

/**
 * Generate an author-reviewable palette candidate from a JSON request.
 *
 * @param {string} configPath
 * @param {{out?: string, preview?: string, overwrite?: boolean}} [options]
 * @param {{cwd?: string}} [ctx]
 * @returns {import('../../theme.type.mjs').ThemePaletteGenerateResponse}
 */
export function themePaletteGenerate(
  configPath,
  options = {},
  {cwd = process.cwd()} = {},
) {
  const resolvedConfig = resolveSafe(configPath, cwd, 'palette config path');
  if (!fs.existsSync(resolvedConfig)) {
    throw new AstryxError(
      `Palette config not found: ${path.relative(cwd, resolvedConfig)}`,
      undefined,
      ERROR_CODES.ERR_FILE_NOT_FOUND,
    );
  }

  let request;
  try {
    request = JSON.parse(fs.readFileSync(resolvedConfig, 'utf-8'));
  } catch (error) {
    throw new AstryxError(
      `Could not parse palette config: ${error instanceof Error ? error.message : String(error)}`,
      undefined,
      ERROR_CODES.ERR_PALETTE_GENERATION,
    );
  }

  let result;
  try {
    result = generatePaletteSet(request);
  } catch (error) {
    throw new AstryxError(
      error instanceof Error ? error.message : String(error),
      undefined,
      ERROR_CODES.ERR_PALETTE_GENERATION,
    );
  }
  if (result.errors.length > 0) {
    throw new AstryxError(
      result.errors
        .map(error => `${error.familyId}: ${error.message}`)
        .join('\n'),
      undefined,
      ERROR_CODES.ERR_PALETTE_GENERATION,
    );
  }

  const candidate = paletteSnapshot(result);
  let candidateText = `${JSON.stringify(candidate, null, 2)}\n`;
  const previewText = options.preview ? renderPalettePreview(candidate) : null;
  let receipt = receiptFor(result, candidateText, previewText);
  let output = null;
  let receiptOutput = null;
  let previewOutput = null;
  let written = false;
  let reason = null;
  const files = [];
  const resolvedTargets = new Set();

  if (options.out) {
    const resolvedOutput = resolveSafe(options.out, cwd, 'palette output path');
    const resolvedReceipt = receiptPathFor(resolvedOutput);
    candidateText = serializeCandidate(candidate, resolvedOutput);
    receipt = receiptFor(result, candidateText, previewText);
    const receiptText = serializeGenerationResult(receipt);
    if (
      resolvedOutput === resolvedConfig ||
      resolvedReceipt === resolvedConfig
    ) {
      throw new AstryxError(
        'Palette output must not replace its input config.',
        undefined,
        ERROR_CODES.ERR_PATH_TRAVERSAL,
      );
    }
    output = path.relative(cwd, resolvedOutput);
    receiptOutput = path.relative(cwd, resolvedReceipt);
    files.push(
      {path: resolvedOutput, next: candidateText},
      {path: resolvedReceipt, next: receiptText},
    );
    resolvedTargets.add(resolvedOutput);
    resolvedTargets.add(resolvedReceipt);
  }

  if (options.preview) {
    const resolvedPreview = resolveSafe(
      options.preview,
      cwd,
      'palette preview path',
    );
    if (!resolvedPreview.endsWith('.html')) {
      throw new AstryxError(
        'Palette preview output must end in .html.',
        undefined,
        ERROR_CODES.ERR_PALETTE_GENERATION,
      );
    }
    if (
      resolvedPreview === resolvedConfig ||
      resolvedTargets.has(resolvedPreview)
    ) {
      throw new AstryxError(
        'Palette preview must not replace an input or another output.',
        undefined,
        ERROR_CODES.ERR_PATH_TRAVERSAL,
      );
    }
    previewOutput = path.relative(cwd, resolvedPreview);
    files.push({path: resolvedPreview, next: previewText});
    resolvedTargets.add(resolvedPreview);
  }

  if (files.length > 0) {
    if (!options.overwrite && files.some(file => fs.existsSync(file.path))) {
      reason = 'exists';
    } else {
      try {
        writeFilesAtomically(files);
        written = true;
      } catch (error) {
        throw new AstryxError(
          `Could not write palette candidate: ${error instanceof Error ? error.message : String(error)}`,
          undefined,
          ERROR_CODES.ERR_WRITE_FAILED,
        );
      }
    }
  }

  return {
    type: 'theme.palette.generate',
    data: {
      recipe: result.recipe,
      status: 'candidate',
      familyCount: result.families.length,
      stopCount: result.request.stops.length,
      modes:
        result.request.modeStrategy === 'light-and-dark'
          ? ['light', 'dark']
          : [result.request.modeStrategy === 'light-only' ? 'light' : 'dark'],
      output,
      receipt: receiptOutput,
      preview: previewOutput,
      written,
      reason,
      candidate,
      generationReceipt: receipt,
    },
  };
}
