// Copyright (c) Meta Platforms, Inc. and affiliates.
export const PALETTE_PREVIEW_VERSION = 'palette-preview-v1';

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function renderRamp(familyId, familyName, mode, colors) {
  const swatches = Object.entries(colors)
    .map(
      ([stop, color]) => `
        <li class="swatch" title="${escapeHtml(`${familyId}.${mode}[${stop}] — ${color}`)}">
          <span class="color" style="--swatch:${escapeHtml(color)}"></span>
          <span class="meta"><strong>${escapeHtml(stop)}</strong><code>${escapeHtml(color)}</code></span>
        </li>`,
    )
    .join('');
  return `
      <section class="family">
        <h3>${escapeHtml(familyName)}</h3>
        <ol class="ramp" style="--stop-count:${Object.keys(colors).length}">${swatches}
        </ol>
      </section>`;
}

function renderMode(candidate, mode) {
  const families = Object.entries(candidate.palette)
    .filter(([, family]) => family[mode])
    .map(([familyId, family]) =>
      renderRamp(familyId, family.name, mode, family[mode]),
    )
    .join('');
  if (!families) return '';
  return `
    <article class="mode ${mode}">
      <header class="mode-title">
        <h2>${mode === 'light' ? 'Light mode' : 'Dark mode'}</h2>
        <span>Generated candidate</span>
      </header>${families}
    </article>`;
}

/**
 * Render a self-contained, deterministic review artifact.
 *
 * @param {import('../../theme.type.mjs').TonalPaletteCandidate} candidate
 * @returns {string}
 */
export function renderPalettePreview(candidate) {
  const modes = ['light', 'dark']
    .map(mode => renderMode(candidate, mode))
    .filter(Boolean)
    .join('');
  const neutralGuidance = candidate.palette.neutral
    ? '<p class="guidance"><strong>Neutral guidance:</strong> use the Neutral family for near-black, near-white, and grayscale roles. Use explicit theme values only when exact black or white is intended.</p>'
    : '';
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="generator" content="${PALETTE_PREVIEW_VERSION}" />
    <title>Astryx palette candidate</title>
    <style>
      :root { color-scheme: light dark; font-family: Inter, ui-sans-serif, system-ui, sans-serif; background: #111; }
      * { box-sizing: border-box; }
      body { margin: 0; background: #111; color: #f5f5f5; }
      main { max-width: 1600px; margin: 0 auto; padding: 40px; }
      h1, h2, h3, p { margin: 0; }
      h1 { font-size: 30px; letter-spacing: -0.03em; }
      .intro { margin: 8px 0 28px; color: #aaa; }
      .notice { margin-bottom: 24px; padding: 12px 14px; border: 1px solid #554c26; border-radius: 10px; background: #2b281a; color: #f2df8b; }
      .guidance { margin: -12px 0 24px; color: #bbb; font-size: 13px; }
      .modes { display: grid; grid-template-columns: 1fr; gap: 24px; }
      .mode { min-width: 0; border-radius: 20px; padding: 24px; overflow-x: auto; }
      .mode.light { background: #f5f5f5; color: #171717; }
      .mode.dark { background: #232323; color: #f5f5f5; border: 1px solid #393939; }
      .mode-title { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 24px; }
      .mode-title span { color: #888; font-size: 13px; }
      .family + .family { margin-top: 28px; }
      .family h3 { margin-bottom: 10px; font-size: 18px; }
      .ramp { display: grid; grid-template-columns: repeat(var(--stop-count), minmax(52px, 1fr)); gap: 8px; margin: 0; padding: 0; list-style: none; }
      .swatch { min-width: 0; }
      .color { display: block; height: 58px; border: 1px solid rgb(127 127 127 / 20%); border-radius: 10px; background: var(--swatch); }
      .meta { display: block; margin-top: 5px; font-size: 11px; line-height: 1.35; }
      .meta strong, .meta code { display: block; overflow: hidden; text-overflow: ellipsis; }
      .meta code { opacity: 0.65; font-family: ui-monospace, monospace; }
      footer { margin-top: 24px; color: #888; font-size: 12px; }
      @media (max-width: 700px) { main { padding: 20px; } }
    </style>
  </head>
  <body data-preview-version="${PALETTE_PREVIEW_VERSION}">
    <main>
      <h1>Astryx tonal palette</h1>
      <p class="intro">Generated by <code>${escapeHtml(candidate.recipe)}</code></p>
      <p class="notice"><strong>Candidate:</strong> review these colors before adopting them. This preview does not certify accessibility.</p>
      ${neutralGuidance}
      <div class="modes">${modes}
      </div>
      <footer>${PALETTE_PREVIEW_VERSION} · self-contained review artifact</footer>
    </main>
  </body>
</html>
`;
}
